# fly.toml app configuration file generated for gpkgtogeojson-backend on 2024-04-09T23:24:35+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gpkgtogeojson-backend'
primary_region = 'arn'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '16gb'
  cpu_kind = 'shared'
  cpus = 8
