name: Visualizer Deployment
on:
  push:
    branches:
      - GCPtesting
jobs:
  deploy:
    name: Deploy Visualizer
    runs-on: ubuntu-latest
    concurrency: deploy-group  
    steps:
        - name: 'Checkout'
          uses: 'actions/checkout@v3'
        - name: 'Google auth'
          id: 'auth'
          uses: 'google-github-actions/auth@v2'
          with:
            credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
        - name: 'Set up Cloud SDK'
          uses: 'google-github-actions/setup-gcloud@v1'
          with:
            project_id: 'fallbekken'
        - name: 'Docker auth'
          run: |-
            gcloud auth configure-docker europe-north1-docker.pkg.dev
        - name: 'Build and push container'
          run: |-
            gcloud builds submit --config=usagecheck/cloudbuild.yaml usagecheck/